# application.yml — главный конфигурационный файл Spring Boot.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

#jwt:
  #secret: your_jwt_secret
  #expiration: 3600000 # 1 час в миллисекундах

  #springdoc:
    #swagger-ui:
    #enabled: true
  #path: /swagger-ui.html

card:
  encryption:
    key: "1234567890abcdef"
